name: MediConnect CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: mediconnect
          MYSQL_DATABASE: mediconnect_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, bcmath, pdo_mysql
        ini-values: post_max_size=256M

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Generate .env.testing file with necessary settings
      run: |
        echo "APP_ENV=testing" >> .env.testing
        echo "DB_CONNECTION=mysql" >> .env.testing
        echo "DB_HOST=127.0.0.1" >> .env.testing
        echo "DB_PORT=3306" >> .env.testing
        echo "DB_DATABASE=mediconnect_testing" >> .env.testing
        echo "DB_USERNAME=root" >> .env.testing
        echo "DB_PASSWORD=kaspastinski" >> .env.testing
        echo "CACHE_STORE=array" >> .env.testing
        echo "MAIL_MAILER=array" >> .env.testing
        echo "QUEUE_CONNECTION=sync" >> .env.testing
        echo "SESSION_DRIVER=array" >> .env.testing
        echo "TELESCOPE_ENABLED=false" >> .env.testing

    - name: Generate application key for testing
      run: php artisan key:generate --env=testing

    - name: Run migrations
      run: php artisan migrate --env=testing --force

    - name: Run tests
      run: php artisan test --env=testing
